# SPDX-FileCopyrightText: (C) 2025 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2025 openRuyi Project Contributors
# SPDX-FileContributor: Zheng Junjie <zhengjunjie@iscas.ac.cn>
# SPDX-FileContributor: misaka00251 <liuxin@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%global srcname gi_docgen
Name:           gi-docgen
Version:        2025.4
Release:        %autorelease
Summary:        Documentation tool for GObject-based libraries
License:        (Apache-2.0 OR GPL-3.0-or-later) AND CC0-1.0 AND MIT AND OFL-1.1
URL:            https://gitlab.gnome.org/GNOME/gi-docgen
#!RemoteAsset
Source0:        https://files.pythonhosted.org/packages/source/g/%{srcname}/%{srcname}-%{version}.tar.gz
BuildSystem:    pyproject

BuildOption(install):  gidocgen

BuildRequires:  make
BuildRequires:  pyproject-rpm-macros
BuildRequires:  python3-devel
BuildRequires:  python3dist(setuptools)
BuildRequires:  python3dist(wheel)
BuildRequires:  python3dist(pip)
BuildRequires:  python3dist(jinja2)
BuildRequires:  python3dist(markdown)
BuildRequires:  python3dist(markupsafe)
BuildRequires:  python3dist(pygments)
BuildRequires:  python3dist(typogrify)

Requires:       python3dist(jinja2)
Requires:       python3dist(markdown)
Requires:       python3dist(markupsafe)
Requires:       python3dist(packaging)
Requires:       python3dist(pygments)
Requires:       python3dist(typogrify)

Provides:       bundled(js-fzy)

%description
GI-DocGen is a document generator for GObject-based libraries. GObject is the
base type system of the GNOME project. GI-Docgen reuses the introspection data
generated by GObject-based libraries to generate the API reference of these
libraries, as well as other ancillary documentation.

GI-DocGen is not a general purpose documentation tool for C libraries.

While GI-DocGen can be used to generate API references for most GObject/C
libraries that expose introspection data, its main goal is to generate the
reference for GTK and its immediate dependencies. Any and all attempts at
making this tool more generic, or to cover more use cases, will be weighted
heavily against its primary goal.

GI-DocGen is still in development. The recommended use of GI-DocGen is to add
it as a sub-project to your Meson build system, and vendor it when releasing
dist archives.

You should not depend on a system-wide installation until GI-DocGen is declared
stable.

%generate_buildrequires
%pyproject_buildrequires

%files -f %{pyproject_files}
%license LICENSES/ .reuse/dep5
%{_bindir}/gi-docgen
%{_mandir}/man1/gi-docgen.1*
# Should we split this into a -devel package in the future? - 251
%{_datadir}/pkgconfig/gi-docgen.pc

%changelog
%{?autochangelog}
