# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: HNO3Miracle <xiangao.or@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%global srcname depyf

Name:           python-%{srcname}
Version:        0.20.0
Release:        %autorelease
Summary:        Decompile Python bytecode and inspect torch.compile output
License:        MIT
URL:            https://github.com/thuml/depyf
VCS:            git:https://github.com/thuml/depyf.git
#!RemoteAsset:  sha256:fb7683bd72c44f67b56029df2c47721e9a02ffa4d7b19095f1c54c4ebf797a98
Source0:        https://files.pythonhosted.org/packages/source/d/%{srcname}/%{srcname}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    pyproject

# Avoid build failures when git is unavailable in the RPM buildroot.
Patch2000:      2000-python-depyf-handle-missing-git-during-version-disc.patch

BuildOption(install):  -l %{srcname}
BuildOption(check):  -e 'depyf.explain*' -e depyf.optimization

BuildRequires:  pyproject-rpm-macros
BuildRequires:  pkgconfig(python3)
BuildRequires:  python3dist(pip)
BuildRequires:  python3dist(setuptools)
BuildRequires:  python3dist(wheel)

Provides:       python3-%{srcname} = %{version}-%{release}
%python_provide python3-%{srcname}

Requires:       python3dist(astor)
Requires:       python3dist(dill)

%description
depyf is a Python bytecode decompiler with optional helpers for inspecting
and debugging code generated by PyTorch's torch.compile pipeline.

%generate_buildrequires
%pyproject_buildrequires

%files -f %{pyproject_files}
%doc README.md
%license LICENSE

%changelog
%autochangelog
