# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: Zheng Junjie <zhengjunjie@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

name: update package to obs
on:
  push:
    branches: [main]
    paths:
     - 'SPECS/**'
concurrency:
  group: update_package
  cancel-in-progress: false

jobs:
  build:
    runs-on: openruyi
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install tools
      run:  sudo dnf install osc obs-build perl-libwww-perl perl-XML-Parser perl-Try-Tiny perl-LWP-Protocol-https -y
    - name: Setup osc config
      run: |
        set -x
        mkdir -p ~/.config/osc
        cat > ~/.config/osc/oscrc <<EOF
        [general]
        apiurl = https://build.openruyi.cn
        [https://build.openruyi.cn]
        pass = ${{ secrets.BOT }}
        user = a-bot
        credentials_mgr_class=osc.credentials.PlaintextConfigFileCredentialsManager
        EOF
    - name: run script
      run: |
        ./scripts/update-package ${{ github.event.before }} ${{ github.sha }}